<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

Exercise 1 

- Subsetting: 'to select'
- indexing: selecting an element
- slicing: selecting a range of elements
- masking: obtaining a portion of elements in a list (using true/false), *allowing only the 'true' subset to be seen*

Exercise 2

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [8]:
np_array_2d[:, 0]    #step1: to give all the first elements

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [13]:
x = np_array_2d[:, 0]
x.astype(int)    # to convert the array elements into integers

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [26]:
y = x.astype(int)
y%2              # to obtain the remainder for the division by 2 

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [32]:
z = y%2
my_mask = z > 0    # to obtain a true-flase list for if it is an odd no. 
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [37]:
np_array_2d[my_mask, 1]  # to obtain the second element of each sublist that correspeonds to a odd no.

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')