<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# Subsetting: Indexing and Slicing

- subset - means to select 
- indexing - selecting one element 
- slicing - selecting a range of elements 

## Lists & Arrays in 1D | Subsetting & Indexing

In [112]:
import numpy as np

In [113]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [114]:
x[0:3] # gives index 0 to 2 

array(['a1', 'b2', 'c3'], dtype='<U3')

In [115]:
x[1:6] # gives index 1 to 5

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [116]:
x[1:6:2] # gives index 1 to 5 but in steps of 2 

array(['b2', 'd4', 'f6'], dtype='<U3')

In [117]:
x[5:] # gives index 5 onwards till th end 

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [118]:
x[5:2:-1]  # gives index 5 to 3 in reverse 

array(['f6', 'e5', 'd4'], dtype='<U3')

In [119]:
x[5:2]    # does not work to give the reverse 

array([], dtype='<U3')

In [120]:
x[::-1]  #reverses the list 

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## Arrays only | subsetting by masking 

masking allows us to sort out some parts of an array

In [121]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [122]:
np_array[my_mask]  #to show only those that true 

array([ 4,  5,  6,  7,  8,  9, 10])

the above can also be done easily w/o introducing another variable:

In [123]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [124]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [125]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [126]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## Lists & Arrays in 2D | Indexing & Slicing

In [127]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [143]:
py_list_2d[3]  #why is the output for this line not shown? is it overrided by the next line?
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [144]:
print(py_list_2d[3]) 
np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U21')

In [129]:
py_list_2d[3]

[4, 'D']

In [130]:
py_list_2d[3][0]  #to find element of first index

4

In [131]:
np_array_2d[3, 0]   #syntax for array always uses a single pair of []

'4'

In [132]:
py_list_2d[:3]  #why is the output for this line not shown again ?
np_array_2d[:3]    #to find first 3 elelments

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [133]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [134]:
py_list_2d[:3][0]  #this gives the first element and not the first elements of all the sublists

[1, 'A']

In [135]:
np_array_2d[:3, 0]  #but np gives the first elements of the sublists!

array(['1', '2', '3'], dtype='<U21')

In [136]:
py_list_2d[3:6][0]

[4, 'D']

In [137]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [138]:
np_array_2d[:, 0] # to print all of the first elements

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

thus, numpy arrayas are more intuitive than lists.

## Growing lists - more efficient with lists than arrays 

In [145]:
x=[1, 2]*5    #creating a alrge list w a small one 
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [150]:
x=[1]       #method 1 in growing a list one element each time
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [151]:
x=[1]    # method 2 in growing a list one element each time
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [153]:
x=[1]       # method 3 in growing a list one element each time
x.append(2)  # using append runs 1.5 times faster than the rest!
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [154]:
x = [1, 2, 3]    #incorporating multiple elements
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [155]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [156]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

## Tuples - similar to lists, but use () and acnnot be changed after creation

In [157]:
a=(1, 2, 3)     # Define tuple

In [158]:
print(a[0])    # Access data

1


In [159]:
# The following will NOT work
a[0]=-1

TypeError: 'tuple' object does not support item assignment

## Be VERY careful when copying

In [160]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [161]:
# DO THIS !
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [139]:



# Your solution here




## Footnotes