<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [7]:
import numpy as np 

# Lists, Arrays & Dictionaries

Python lists 

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] 
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Numpy Arrays 

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionary - able to hold the 2 lists in one structure 

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man", 
    "Stephen Strange": "Doctor Strange"
}

## Accessing data from a list (or array)
python starts from 0

In [6]:
py_real_names[0]

'Natasha Romanoff'

using a negative index allowa us to count fron the back, thus -1 will give the last element 

In [7]:
py_super_names[-1]

'Doctor Strange'

In [8]:
py_super_names[-2]

'Iron Man'

## Accessing data from a dictionary

In [9]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [10]:
superhero_info.keys()   #this is to access all the keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values() # this is to access all the values 

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## Higher dimensional lists
store the lists in a 2D list 

In [12]:
py_superhero_info = [ ['Natasha Romanoff', 'Black Widow'], 
                      ['Tony Stark', 'Iron Man'], 
                      ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays


to create a new numpy array with a python list,

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
np_array_2d = np.array(py_list_2d) 

to find the number of elements in a list or array, 

In [14]:
len(py_list_2d)

10

In [16]:
len(np_array_2d)

10

In [19]:
np_array_2d.shape   # shape is not a function, it is an attribute of numpy array

(10, 2)

## Arrays are fussy about type
arrays insist on having only 1 single data type. but this is just annoying, not a problem 

In [23]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [21]:
py_list

[1, 1.5, 'A']

In [22]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## Adding a number - only works for arrays 

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [25]:
np_array + 10

array([11, 12, 13, 14, 15])

In [26]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

## Adding another list

In [27]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [29]:
py_list_1 + py_list_2    #this will give u all the elements in both lists 

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [30]:
np_array_1 + np_array_2   # this will cause addition of the elements accordingly

array([11, 22, 33, 44, 55])

## Multiplying by a Number

In [6]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [32]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
for n in py_list:
    print(n*2, end=', ')

2, 4, 6, 8, 10, 

In [33]:
np_array*2

array([ 2,  4,  6,  8, 10])

## Squaring

In [34]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [35]:
py_list**2    # this wont work 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Asking questions

In [5]:
py_list == 3  #asking if the whole list is equal to integer 3, so it will always be false 

False

In [37]:
np_array == 3 

array([False, False,  True, False, False])

In [38]:
np_array > 3

array([False, False, False,  True,  True])

## Mathematics
take note of the functions needed for list vs arrays 

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [40]:
sum(py_list)

15

In [41]:
max(py_list)

5

In [42]:
min(py_list)

1

In [43]:
np_array.sum()

15

In [44]:
np_array.max()

5

In [45]:
np_array.min()

1

In [46]:
np_array.mean()

3.0

In [47]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes